ruby/stocking/config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  # get 'home/index'
  root 'home#index'
  get 'home/about'

  post "/" => 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

ruby/stocking/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ruby/stocking/app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
    validates :ticker, presence: true
    validates :ticker, format: {without: /\s/}
end

ruby/stocking/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          has_many :stocks
end

ruby/stocking/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby/stocking/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'finnhub_ruby'
    finhub_key = ENV['FINHUB_API_KEY']
    FinnhubRuby.configure do |config|
      config.api_key['api_key'] = finhub_key.to_str
    end
    
    finnhub_client = FinnhubRuby::DefaultApi.new
    if params[:ticker] == ""
      @nothing = "Please enter a symbol before searching"
    elsif params[:ticker]
      @symbol_input = params[:ticker]
      @rtprice = finnhub_client.quote(@symbol_input)
      @profile = finnhub_client.company_profile2({symbol: @symbol_input})
      # @financials = finnhub_client.company_basic_financials(@symbol_input, 'all')
      if finnhub_client.symbol_search(@symbol_input).count == 0
        @error = "Please check the symbol that has been entered"
      end
    end
  end

  def about
  end
end

ruby/stocking/app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  before_action :correct_user, only: %i[edit update destroy]
  before_action :authenticate_user!

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ticker = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: "Not Authorised to edit this stock" if @ticker.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

ruby/stocking/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/stocking/app/helpers/home_helper.rb
module HomeHelper
end

ruby/stocking/app/helpers/stocks_helper.rb
module StocksHelper
end

ruby/stocking/app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button class="btn-close" data-bs-dismiss="alert">
        </button>
        <%= content_tag(:div, msg)%>
    </div>
<% end %>

ruby/stocking/app/views/home/_footer.html.erb
<br/><br/><br/><br/><br/><br/><br/>
<center>Copyright (c) Aloke Mascarenhas</center>

ruby/stocking/app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div class="container-fluid">
  <%= link_to "Stocking", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to "About", home_about_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Show Stocks", stocks_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Stocks", new_stock_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up",  new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form action="{% url 'home' %}" class="d-flex" method="POST">
        <input class="form-control me-2" type="search" placeholder="Enter Stock Symbol" aria-label="Search" name="ticker">
        <button class="btn btn-outline-success text-nowrap" type="submit">Stock Quote</button>
    </form>
</div>
</nav>

ruby/stocking/app/views/home/about.html.erb
<h1>About Me!</h1>
<p>Hello my name is Bob</p>

ruby/stocking/app/views/home/index.html.erb
<h1>Stocking</h1>

<br/>
<%= form_tag root_path :method => 'POST' do %>
    <%= text_field_tag 'ticker', nil, placeholder: "Enter Ticker Symbol", size: 50 %>
    <%= submit_tag 'Lookup' %>
<% end %>

<br/><br/><br/>
<% if @error %>
    <%= @error %> <br/>
<% elsif @symbol_input %>
    <img src="<%= @profile.logo %>"><br/>
    Company Name : <%= @profile.name %> <br/>
    Company Ticker : <%= @symbol_input %><br/>
    Price : $ <%= @rtprice.c %> <br/>
    Previous Close : $ <%= @rtprice.pc %> <br/>
    Market Cap : $ <%= @profile.market_capitalization %> <br/>
<% elsif @nothing %>
    <%= @nothing %> <br/>
<% end %>

ruby/stocking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock Market App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'home/navbar' %>
    <br/><br/>
    <div class="container">

      <%= render 'home/flash' %>

      <%= yield %>
    </div>
  </body>
    
<%= render 'home/footer' %>

</html>

ruby/stocking/app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ticker, style: "display: block" %>
    <%= form.text_field :ticker %>
  </div>

  <div>
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :stock_user_id, value: current_user.id, type: :hidden%>

  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

ruby/stocking/app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">

<%if @stock.ticker == ""%>
  
<% else %>
  <% require 'finnhub_ruby' %>
  <% finhub_key = ENV['FINHUB_API_KEY'] %>
  <% FinnhubRuby.configure do |config|%>
    <% config.api_key['api_key'] = finhub_key.to_str%>
  <% end %>
  <% finnhub_client = FinnhubRuby::DefaultApi.new %>
  <%rtprice = finnhub_client.quote(stock.ticker)%>
  <%profile = finnhub_client.company_profile2({symbol: stock.ticker})%>
  <strong><%= profile.name %></strong><br/>
  Ticker : <%= profile.ticker%><br/>
  Current Price : $ <%= number_with_precision(rtprice.c, :precision => 2, :delimiter =>',') %><br/>
  Previous Close :$ <%= number_with_precision(rtprice.pc, :precision => 2, :delimiter =>',') %><br/>
  Market Capitalization (000s) : $ <%= number_with_precision(profile.market_capitalization, :precision => 0, :delimiter =>',') %><br/>
  Industry: <%= profile.finnhub_industry %><br/>
  <img src="<%= profile.logo %>" class="img-thumbnail"><br/>

<% end %>

</div>

ruby/stocking/app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Show this stock", @stock %> |
  <%= link_to "Back to stocks", stocks_path %>
</div>

ruby/stocking/app/views/stocks/index.html.erb
<h1>Stocks</h1>

<div id="stocks">
  <table class="table table-striped table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Ticker</th>
        <th scope="col">Company Name</th>
        <th scope="col">Current Price</th>
        <th scope="col">Previous Close</th>
        <th scope="col">Market Cap (000's)</th>
      </tr>
    </thead>
    <tbody>
      <% @stocks.each do |stock| %>
        <%if stock.user_id == current_user.id%>

          <% require 'finnhub_ruby' %>
          <% finhub_key = ENV['FINHUB_API_KEY'] %>
          <% FinnhubRuby.configure do |config|%>
            <%config.api_key['api_key'] = finhub_key.to_str%>
          <%end %>
        
          <% finnhub_client = FinnhubRuby::DefaultApi.new %>
          <%if stock.ticker == ""%>
              <%= @profile.ticker = "N/A"%>
              <%= @profile.name = "N/A"%>
              <%= @rtprice.c = "N/A"%>
              <%= @rtprice.pc = "N/A"%>
              <%= @profile.market_capitalization = "N/A"%>
          <%elsif stock.ticker %>
            <%@rtprice = finnhub_client.quote(stock.ticker)%>
            <%@profile = finnhub_client.company_profile2({symbol: stock.ticker})%>
            <%if finnhub_client.symbol_search(stock.ticker).count == 0%>
              <%= @profile.ticker = "N/A"%>
              <%= @profile.name = "N/A"%>
              <%= @rtprice.c = "N/A"%>
              <%= @rtprice.pc = "N/A"%>
              <%= @profile.market_capitalization = "N/A"%>
            <%end%>
          <%end%>
        <tr>
          <td><%= @profile.ticker%></td>
          <td><%= link_to @profile.name, stock %></td>
          <td>$ <%= number_with_precision(@rtprice.c, :precision => 2, :delimiter =>',') %></td>
          <td>$ <%= number_with_precision(@rtprice.pc, :precision => 2, :delimiter =>',') %></td>
          <td>$ <%= number_with_precision(@profile.market_capitalization, :precision => 0, :delimiter =>',') %></td>
          <td><center><%= link_to 'Edit', edit_stock_path(stock) %></center></td>
          <td><center><%= link_to 'Delete', stock,
          method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger'%></center></td>
        </tr>
        <%end%>
      <%end%>
    </tbody>
  </table>
</div>

<%= link_to "New stock", new_stock_path %>

ruby/stocking/app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Back to stocks", stocks_path %>
</div>

ruby/stocking/app/views/stocks/show.html.erb
<div class="col-md-6 offset-md-3">
  <div class="bg-secondary bg-gradient w-auto p-3 d-grid gap-5">

    <%= render @stock %>

    <div>
      <%= link_to "Back to stocks", stocks_path, class: "btn btn-dark"%>
    </div>

  </div>
</div>